// Package flow renders flow definitions (ordered pipeline steps) into the
// PowerShell job scripts executed by Windows agents.
package flow

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/badskater/encode-system/backend/internal/model"
)

// Vars carries the node-side paths and release metadata shared by all jobs.
type Vars struct {
	BinDir     string // tools directory on the node, e.g. C:\bin
	ScriptsDir string // NFS scripts mount on the node, e.g. C:\Encodes\scripts
	ReleaseDir string // NFS release mount on the node, e.g. C:\Encodes\ReleaseFolders
	Group      string // release group tag, e.g. OldFartsSubs
	Tag        string // quality tag, e.g. 1080p
}

// DefaultX265Args mirrors the legacy batch script's x265 invocation so flows
// start with the proven parameter set.
const DefaultX265Args = "--frame-threads 1 --lookahead-slices 8 --input-depth 10 --output-depth 10 " +
	"--videoformat ntsc --range limited --colorprim bt709 --transfer bt709 --colormatrix bt709 " +
	"--allow-non-conformance --preset slow --crf 15 --deblock=-2:-2 --min-keyint 23 --keyint 240 " +
	"--ref 6 --bframes 12 --b-adapt 2 --b-pyramid --b-intra --fades --aq-mode 5 --aq-strength 0.80 " +
	"--aq-strength-edge 0.90 --aq-bias-strength 0.95 --aq-bias-strength-edge 1.00 --subme 7 --me star " +
	"--merange 24 --qcomp 0.82 --rc-lookahead 160 --rd 6 --rdoq-level 2 --psy-rd 2.0 --psy-rdoq 2.0 " +
	"--open-gop --cbqpoffs -2 --crqpoffs -2 --qpstep 2 --weightb --rect --amp --tu-intra-depth 2 " +
	"--tu-inter-depth 2 --tskip --ctu 32 --max-tu-size 16 --rskip 0 --no-strong-intra-smoothing " +
	"--no-sao --no-sao-non-deblock"

// DefaultFlow is the standard 1080p pipeline matching the legacy batch scripts.
func DefaultFlow() *model.Flow {
	return &model.Flow{
		Name: "default-1080",
		Steps: []model.Step{
			{Type: model.StepSourceRename, Params: map[string]string{"source_name": "src"}},
			{Type: model.StepDGIndex},
			{Type: model.StepAudio, Params: map[string]string{"track": "2", "bitrate": "320"}},
			{Type: model.StepEncode, Params: map[string]string{"x265_args": DefaultX265Args}},
			{Type: model.StepMux},
			{Type: model.StepReleaseCopy},
			{Type: model.StepKeyframes},
		},
	}
}

var knownSteps = map[model.StepType]bool{
	model.StepSourceRename: true,
	model.StepDGIndex:      true,
	model.StepAudio:        true,
	model.StepEncode:       true,
	model.StepMux:          true,
	model.StepReleaseCopy:  true,
	model.StepKeyframes:    true,
}

// psQuote renders a PowerShell single-quoted string literal, escaping embedded
// single quotes by doubling them. All rendered values pass through here, which
// keeps generated scripts injection-safe for arbitrary series names.
func psQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

var episodeRe = regexp.MustCompile(`Ep\s*(\d+)`)

// EpisodeNumber extracts the episode number from a folder name like "Ep 01",
// preserving the folder's zero-padding so output names match the legacy
// convention ("- 01"). Falls back to the raw dir suffix when no pattern matches.
func EpisodeNumber(dir string) string {
	if m := episodeRe.FindStringSubmatch(dir); m != nil {
		return m[1]
	}
	parts := strings.Split(strings.TrimRight(dir, `/\`), string('/'))
	last := parts[len(parts)-1]
	return last
}

// OutputName computes the final MKV name: "<Series> - <Episode> [<Tag>].mkv".
func OutputName(series, episode, tag string) string {
	return fmt.Sprintf("%s - %s [%s].mkv", series, episode, tag)
}

// ReleaseFolderName computes "[<Group>] <Series> - Raws [<Tag>]".
func ReleaseFolderName(group, series, tag string) string {
	return fmt.Sprintf("[%s] %s - Raws [%s]", group, series, tag)
}

// param fetches a step parameter with a fallback default.
func param(step model.Step, key, def string) string {
	if v, ok := step.Params[key]; ok && v != "" {
		return v
	}
	return def
}

// Render produces the complete PowerShell script for one job. The script
// expects -LibPath pointing at EncodeLib.ps1 on the agent (dot-sourced).
func Render(f *model.Flow, j *model.Job, v Vars) (string, error) {
	if f == nil || len(f.Steps) == 0 {
		return "", fmt.Errorf("flow %q has no steps", name(f))
	}
	for i, st := range f.Steps {
		if !knownSteps[st.Type] {
			return "", fmt.Errorf("flow %q step %d: unknown step type %q", f.Name, i, st.Type)
		}
	}
	if j.Series == "" || j.EpisodeDir == "" {
		return "", fmt.Errorf("job missing series/episode dir")
	}

	episode := j.Episode
	if episode == "" {
		episode = EpisodeNumber(j.EpisodeDir)
	}
	scriptName := episode + "." + j.ScriptType // e.g. "01.vpy" rendered below as 1080.<ext>

	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by encode-system controller — job %d, flow %s\n", j.ID, f.Name)
	b.WriteString("param([Parameter(Mandatory=$true)][string]$LibPath)\n")
	b.WriteString("Set-StrictMode -Version Latest\n")
	b.WriteString("$ErrorActionPreference = 'Stop'\n")
	b.WriteString(". $LibPath\n\n")

	b.WriteString("# --- Job variables ---\n")
	fmt.Fprintf(&b, "$BinDir     = %s\n", psQuote(v.BinDir))
	fmt.Fprintf(&b, "$ScriptsDir = %s\n", psQuote(v.ScriptsDir))
	fmt.Fprintf(&b, "$ReleaseDir = %s\n", psQuote(v.ReleaseDir))
	fmt.Fprintf(&b, "$Series     = %s\n", psQuote(j.Series))
	fmt.Fprintf(&b, "$Episode    = %s\n", psQuote(episode))
	fmt.Fprintf(&b, "$EpisodeDir = Join-Path $ScriptsDir %s\n", psQuote(j.EpisodeDir))
	fmt.Fprintf(&b, "$ScriptFile = Join-Path $EpisodeDir %s\n", psQuote("1080."+j.ScriptType))
	fmt.Fprintf(&b, "$Tag        = %s\n", psQuote(v.Tag))
	fmt.Fprintf(&b, "$Group      = %s\n", psQuote(v.Group))
	fmt.Fprintf(&b, "$OutputName = %s\n", psQuote(OutputName(j.Series, episode, v.Tag)))
	fmt.Fprintf(&b, "$ReleaseFolder = %s\n\n", psQuote(ReleaseFolderName(v.Group, j.Series, v.Tag)))

	for i, st := range f.Steps {
		call, err := renderStep(st, j)
		if err != nil {
			return "", fmt.Errorf("flow %q step %d (%s): %w", f.Name, i, st.Type, err)
		}
		fmt.Fprintf(&b, "# --- Step %d: %s ---\n", i+1, st.Type)
		fmt.Fprintf(&b, "Write-Output \"ENCODE_STEP %s start\"\n", st.Type)
		fmt.Fprintf(&b, "try {\n%s\n} catch {\n", call)
		fmt.Fprintf(&b, "    Write-Output \"ENCODE_STEP_FAILED %s $($_.Exception.Message)\"\n", st.Type)
		b.WriteString("    exit 1\n}\n\n")
	}

	b.WriteString("Write-Output \"ENCODE_JOB_DONE\"\n")
	_ = scriptName
	return b.String(), nil
}

func name(f *model.Flow) string {
	if f == nil {
		return ""
	}
	return f.Name
}

// renderStep emits the EncodeLib function call for one step.
func renderStep(st model.Step, j *model.Job) (string, error) {
	switch st.Type {
	case model.StepSourceRename:
		return fmt.Sprintf("    Invoke-SourceRename -EpisodeDir $EpisodeDir -SourceName %s",
			psQuote(param(st, "source_name", "src"))), nil

	case model.StepDGIndex:
		return "    Invoke-DgIndex -BinDir $BinDir -EpisodeDir $EpisodeDir", nil

	case model.StepAudio:
		return fmt.Sprintf("    Invoke-AudioExtract -BinDir $BinDir -EpisodeDir $EpisodeDir -TrackIndex %s -Bitrate %s",
			psQuote(param(st, "track", "2")), psQuote(param(st, "bitrate", "320"))), nil

	case model.StepEncode:
		return fmt.Sprintf("    Invoke-VideoEncode -BinDir $BinDir -EpisodeDir $EpisodeDir -ScriptFile $ScriptFile -OutputFile (Join-Path $EpisodeDir %s) -X265Args %s",
			psQuote("1080.hevc"), psQuote(param(st, "x265_args", DefaultX265Args))), nil

	case model.StepMux:
		return "    Invoke-Mux -BinDir $BinDir -EpisodeDir $EpisodeDir -OutputName $OutputName", nil

	case model.StepReleaseCopy:
		return "    Invoke-ReleaseCopy -EpisodeDir $EpisodeDir -ReleaseDir $ReleaseDir -ReleaseFolder $ReleaseFolder -OutputName $OutputName", nil

	case model.StepKeyframes:
		return "    Invoke-Keyframes -BinDir $BinDir -ReleaseDir $ReleaseDir -ReleaseFolder $ReleaseFolder -Series $Series -Episode $Episode -OutputName $OutputName", nil
	}
	return "", fmt.Errorf("no renderer for step type %q", st.Type)
}
